### ISSUE TITLE
Has the PALADIN project been abandoned?

### ISSUE THREAD

**Issue by hermidalc** [ToniWestbrook/paladin#47]
There isn't any commit activity since 2019 and issues haven't been responded to since then either. This would be a very useful tool for a tool I'm developing, as an alternative to using DIAMOND for my needs.

**Comment by ToniWestbrook** [comment]
Hi @hermidalc - thanks for checking in on the project, I can understand not wanting to incorporate an abandoned tool into your pipeline.  It definitely is still maintained and used, we use it daily at UNH and it gets cited regularly as well, so I know other folks are using it out there too. I haven't had any reports of any major bugs lately which is why there haven't been any updates in a while, and I haven't had a lot of extra time to work on smaller requests.  But we do answer most tickets that come in, there may have been a couple that I missed though.  Let me know if you have any questions about it though. Thanks!

**Comment by hermidalc** [comment]
Thanks very much @ToniWestbrook I just wanted to check! PALADIN looks to be a very interesting alternative to DIAMOND.
